name: personalities

channels: 
  - conda-forge

dependencies: 
  - python=3.12
  - gensim=4.3
  - matplotlib=3.9
  - nltk=3.8
  - pandas=2.2
  - pypdf2=2.11
  - spacy=3.7
  - textblob=0.15
  - vaderSentiment=3.3
  - wordcloud=1.9
